version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build:
    working_directory: /usr/src/app
    docker:
      - image: avarona/browser-test:latest
    steps:
      - checkout
      - run:
          name: Setup screenshots
          command: mkdir /tmp/screenshots
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Start script
          command: yarn start
      - store_artifacts:
          path: /tmp/screenshots
workflows:
  build:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
