version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build:
    docker:
      - image: avarona/browser-test:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn start
workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
